/*
 * Progress deck — ITRI / NTUT, reporting period to 2026-09-01.
 * Same nathan-deck design system as build_midterm_deck.js (tokens unchanged).
 *
 * THE TWO RULES, inherited and still enforced:
 *
 *   1. Every number on a slide is READ FROM THE ARTEFACTS at build time. A
 *      slide cannot drift from the data it claims to report. This period that
 *      rule earned its keep: a metric that had been quoted for a week turned
 *      out to measure something else, and the only reason the correction is
 *      cheap is that the deck regenerates from disk.
 *
 *   2. No video is embedded. A previous deck reached 486 MB that way. Videos
 *      ship alongside, by filename.
 */

const pptxgen = require("pptxgenjs");
const React = require("react");
const ReactDOMServer = require("react-dom/server");
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const {
  FaBullseye, FaShieldAlt, FaEye, FaChartBar, FaExclamationTriangle,
  FaClipboardCheck, FaTasks, FaRoad, FaMicrochip, FaCity, FaWalking,
  FaFileContract, FaVials, FaLock, FaGlobeAsia,
} = require("react-icons/fa");

/* ── DESIGN TOKENS (authoritative, unchanged) ──────────────────────────── */
const TEAL = "249DB2";
const TEAL_DK = "1A7484";
const TEAL_TINT = "EAF6F8";
const BLACK = "1A1A1A";
const INK = "2B2B2B";
const GREY = "6B7280";
const WHITE = "FFFFFF";
const LINE = "E3E8EC";
const FF = "Poppins";

const REPO = "D:/OneDrive/College/S2-TaipeiTech/Lab/VLA Drone";

/* ── DATA LOADING ──────────────────────────────────────────────────────── */
function readJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(REPO, rel), "utf8"));
}
function metrics(tag) { return readJson(`demo/out/${tag}/metrics.json`); }
function kpi(tag) { return readJson(`demo/out/${tag}/kpi.json`); }
function has(tag) { return fs.existsSync(path.join(REPO, "demo/out", tag, "metrics.json")); }

/* Numbers the new slides need that no flight artefact carries — the altitude
 * curve before the fix, the constraint inventory, bundle facts, the rate gate.
 * Generated by tools/build_deck_data.py, which cross-checks its altitude model
 * against the live Shield and refuses to write the file if they disagree. Rule
 * 1 holds: still read from an artefact, still not typed onto a slide. */
const EXTRA = readJson("docs/data/deck_sept_extra.json");
const SWEEP = readJson("docs/data/scenario_sweep.json");

function videoMb(rel) {
  const p = path.join(REPO, rel);
  return fs.existsSync(p) ? (fs.statSync(p).size / 1048576).toFixed(1) + " MB" : "pending";
}

/* Tracking accuracy, recomputed here from the flight log rather than trusted:
 * the same projection demo/track_truth.py uses. Quoting a stored number would
 * reintroduce exactly the problem this period uncovered.
 *
 * It mirrors the Python including the 2026-09-07 fix, and it has to. Both
 * versions first read `tgt_x/tgt_y`, which is the CAR. On a flight that
 * retargets to a person that is the wrong object, every later detection scores
 * as a miss, and this slide would report a detector failure that never
 * happened. A row now carries `truth.pts` for whatever the subject is at that
 * tick; a row without it is UNSCORABLE, counted and never scored. */
function readRows(tag) {
  const p = path.join(REPO, "demo/out", tag, "flight_log.jsonl");
  if (!fs.existsSync(p)) return null;
  return fs.readFileSync(p, "utf8").split("\n").filter((l) => l.trim()).map(JSON.parse);
}

function truthPts(r) {
  // Mirrors demo/track_truth.truth_points EXACTLY, including the early return:
  // once a row carries a `truth` object it is authoritative, and an EMPTY or
  // ABSENT `pts` means unscorable. Falling through to tgt_x/tgt_y here would
  // score a pedestrian phase against the car again - the very defect this
  // mirrors - and would put 0.406 back on a slide while metrics.json said
  // 0.931. A review found three ways this had drifted from the Python: a null
  // or absent `pts` still fell through to the car, the psi guard tested
  // `undefined` where Python tests None, and only tgt_x was required where
  // Python requires both. tests/test_deck_scorer_parity.py runs this function
  // under node against the Python on the same rows.
  if (r.truth) return (Array.isArray(r.truth.pts) && r.truth.pts.length) ? r.truth.pts : null;
  if (r.tgt_x !== null && r.tgt_x !== undefined &&
      r.tgt_y !== null && r.tgt_y !== undefined) return [[r.tgt_x, r.tgt_y]];
  return null;
}

function scoreRows(rows) {
  const errs = [];
  const cands = [];
  let outOfFov = 0;
  let unscorable = 0;
  for (const r of rows) {
    if (!r.det || r.psi === null || r.psi === undefined) continue;
    const pts = truthPts(r);
    if (!pts) { unscorable++; continue; }
    const W = r.det.img_w || 400;
    let bestIn = null;
    let bestAny = null;
    let nIn = 0;
    for (const pt of pts) {
      let rel = Math.atan2(pt[1] - r.y, pt[0] - r.x) - r.psi;
      rel = Math.atan2(Math.sin(rel), Math.cos(rel));
      const deg = (rel * 180) / Math.PI;
      const e = Math.abs(r.det.cx - W * (0.5 + deg / 90));
      if (bestAny === null || e < bestAny) bestAny = e;
      // Only a subject actually IN SHOT may be credited with the box - the
      // Python does the same. Taking the min over all candidates let a row be
      // scored on target against a subject behind the aircraft.
      if (Math.abs(deg) <= 45) { nIn++; if (bestIn === null || e < bestIn) bestIn = e }
    }
    if (nIn > 0) { errs.push(bestIn); cands.push(nIn) }
    else { errs.push(bestAny); cands.push(0); outOfFov++ }
  }
  // A phase with nothing scorable still has something to say - how many
  // detections could not be judged. Returning bare null here would throw that
  // away and leave callers dereferencing nothing.
  if (!errs.length) {
    return { n: 0, unscorable, median: null, p95: null, onTarget: null,
             candidates: null, outOfFov: 0 };
  }
  const s = errs.slice().sort((a, b) => a - b);
  const c = cands.slice().sort((a, b) => a - b);
  return {
    n: errs.length,
    unscorable,
    median: s[Math.floor(s.length / 2)],
    p95: s[Math.min(s.length - 1, Math.floor(0.95 * s.length))],
    onTarget: errs.filter((e) => e <= 100).length / errs.length,
    // How many acceptable subjects were in shot. 1 means the figure is
    // comparable with the single-target flights; more means it is not, and the
    // Python reports a chance floor beside it for that reason.
    candidates: c[Math.floor(c.length / 2)],
    outOfFov,
  };
}

function trackAccuracy(tag) {
  const rows = readRows(tag);
  return rows === null ? null : scoreRows(rows);
}

/* The retarget flight, split at the tick the subject changed. Two numbers,
 * because it IS two numbers: one phase has logged truth and one does not, and
 * a single figure spanning both says nothing about either. */
function retargetSplit(tag) {
  const rows = readRows(tag);
  if (!rows) return null;
  const ev = (metrics(tag).retargets || [])[0];
  if (!ev) return null;
  return {
    ev,
    ticks: rows.length,
    pre: scoreRows(rows.filter((r) => r.tick < ev.tick)),
    post: scoreRows(rows.filter((r) => r.tick >= ev.tick)),
  };
}

/* Findings written in this reporting period, counted rather than typed. */
function findingsSince(prefix) {
  const dir = path.join(REPO, "docs");
  return fs.readdirSync(dir)
    .filter((f) => f.startsWith("FINDING-") && f.endsWith(".md"))
    .filter((f) => fs.readFileSync(path.join(dir, f), "utf8")
      .includes("**Date:** " + prefix)).length;
}

const n = (v, d = 2) => (v === null || v === undefined ? "n/a" : Number(v).toFixed(d));
const pct = (v) => (v === null || v === undefined ? "n/a" : (Number(v) * 100).toFixed(1) + " %");

async function iconPng(Icon, color = "#" + TEAL, size = 256) {
  const svg = ReactDOMServer.renderToStaticMarkup(
    React.createElement(Icon, { color, size: String(size) }));
  const buf = await sharp(Buffer.from(svg)).png().toBuffer();
  return "image/png;base64," + buf.toString("base64");
}

async function main() {
  const pres = new pptxgen();
  pres.layout = "LAYOUT_16x9";
  pres.title = "Safety-Constrained VLA for ArduPilot UAVs — Progress, September 2026";
  pres.author = "Nathanael Tjahyadi";

  const ic = {
    aim: await iconPng(FaBullseye),
    shield: await iconPng(FaShieldAlt),
    eye: await iconPng(FaEye),
    chart: await iconPng(FaChartBar),
    warn: await iconPng(FaExclamationTriangle),
    check: await iconPng(FaClipboardCheck),
    tasks: await iconPng(FaTasks),
    road: await iconPng(FaRoad),
    chip: await iconPng(FaMicrochip),
    city: await iconPng(FaCity),
    walk: await iconPng(FaWalking),
    rules: await iconPng(FaFileContract),
    vials: await iconPng(FaVials),
    lock: await iconPng(FaLock),
    globe: await iconPng(FaGlobeAsia),
  };

  /* ── SHARED HELPERS (nathan-deck geometry, copied verbatim) ──────────── */
  function badge(s, i) {
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: 9.3, y: 5.18, w: 0.5, h: 0.32,
      fill: { color: TEAL }, line: { color: TEAL }, rectRadius: 0.06,
    });
    s.addText(String(i).padStart(2, "0"), {
      x: 9.3, y: 5.18, w: 0.5, h: 0.32,
      fontSize: 9, color: WHITE, fontFace: FF, bold: true,
      align: "center", valign: "middle",
    });
  }

  function heading(s, eyebrow, title, x = 0.55, y = 0.45) {
    s.addText(eyebrow.toUpperCase(), {
      x, y, w: 8.5, h: 0.28,
      fontSize: 10, color: TEAL, fontFace: FF, bold: true, charSpacing: 2,
    });
    s.addText(title, {
      x, y: y + 0.3, w: 8.9, h: 0.6,
      fontSize: 26, color: BLACK, fontFace: FF, bold: true,
    });
    s.addShape(pres.shapes.LINE, {
      x, y: y + 0.98, w: 0.9, h: 0, line: { color: TEAL, width: 2.5 },
    });
  }

  function card(s, x, y, w, h, iconData, titleTxt, bodyTxt) {
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x, y, w, h, fill: { color: WHITE }, line: { color: LINE, width: 1 },
      rectRadius: 0.08,
      shadow: { type: "outer", blur: 6, offset: 2, angle: 90, color: "D9DEE3", opacity: 0.4 },
    });
    let ty = y + 0.22;
    if (iconData) {
      s.addImage({ data: iconData, x: x + 0.22, y: y + 0.22, w: 0.36, h: 0.36 });
      s.addText(titleTxt, {
        x: x + 0.68, y: y + 0.2, w: w - 0.9, h: 0.4,
        fontSize: 13, color: INK, fontFace: FF, bold: true, valign: "middle",
      });
      ty = y + 0.72;
    } else {
      s.addText(titleTxt, {
        x: x + 0.24, y: y + 0.2, w: w - 0.48, h: 0.4,
        fontSize: 13, color: INK, fontFace: FF, bold: true,
      });
      ty = y + 0.66;
    }
    if (bodyTxt) {
      // A card shorter than its own header leaves negative room for the body,
      // and pptxgenjs emits <a:ext cy="-100584">. PowerPoint then refuses the
      // WHOLE package with no clue which shape caused it. Guard, do not debug.
      const bodyH = h - (ty - y) - 0.2;
      if (bodyH <= 0) {
        throw new Error(
          `card "${titleTxt}" is ${h}" tall but its header needs ` +
          `${(ty - y + 0.2).toFixed(2)}", leaving ${bodyH.toFixed(2)}" for the body. ` +
          `Negative extents make the whole deck unopenable. Raise h to at least ` +
          `${(ty - y + 0.45).toFixed(2)}".`);
      }
      s.addText(bodyTxt, {
        x: x + 0.24, y: ty, w: w - 0.48, h: bodyH,
        fontSize: 11, color: GREY, fontFace: FF, lineSpacingMultiple: 1.25, valign: "top",
      });
    }
  }

  function darkBase(s, eyebrow) {
    s.background = { color: TEAL_DK };
    s.addShape(pres.shapes.RECTANGLE, {
      x: 0, y: 0, w: 0.09, h: 5.625, fill: { color: TEAL }, line: { color: TEAL },
    });
    if (eyebrow) {
      s.addText(eyebrow.toUpperCase(), {
        x: 0.55, y: 0.5, w: 9, h: 0.3,
        fontSize: 10, color: TEAL_TINT, fontFace: FF, bold: true, charSpacing: 3,
      });
    }
  }

  function table(s, rows, colFrac, x, y, rh, emphasis = []) {
    const tw = 8.9;
    const colW = colFrac.map((f) => tw * f);
    rows.forEach((r, ri) => {
      let cx = x;
      r.forEach((cell, ci) => {
        const header = ri === 0;
        const zebra = !header && ri % 2 === 0;
        const emph = emphasis.some(([a, b]) => a === ri && b === ci);
        s.addShape(pres.shapes.RECTANGLE, {
          x: cx, y: y + ri * rh, w: colW[ci], h: rh,
          fill: { color: header ? TEAL : zebra ? TEAL_TINT : WHITE },
          line: { color: LINE, width: 1 },
        });
        s.addText(String(cell), {
          x: cx + 0.1, y: y + ri * rh, w: colW[ci] - 0.2, h: rh,
          fontSize: header ? 11.5 : 11,
          color: header ? WHITE : emph ? TEAL : INK,
          bold: header || emph, fontFace: FF,
          align: ci === 0 ? "left" : "center", valign: "middle",
        });
        cx += colW[ci];
      });
    });
  }

  let SLIDE = 0;
  const next = () => ++SLIDE;

  /* ── 01 · COVER ─────────────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    darkBase(s, "ITRI · NTUT AIoT Laboratory · Feb–Nov 2026");
    s.addText("Semantic-Spatial Translation and\nSafety-Constrained VLA for ArduPilot UAVs", {
      x: 0.55, y: 1.5, w: 8.9, h: 1.4,
      fontSize: 30, color: WHITE, fontFace: FF, bold: true, lineSpacingMultiple: 1.1,
    });
    s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: 0.55, y: 3.15, w: 3.5, h: 0.42,
      fill: { color: TEAL }, line: { color: TEAL }, rectRadius: 0.1,
    });
    s.addText("Progress report · September 2026", {
      x: 0.55, y: 3.15, w: 3.5, h: 0.42,
      fontSize: 11, color: WHITE, fontFace: FF, bold: true,
      align: "center", valign: "middle",
    });
    s.addText("Nathanael Tjahyadi · Guardrail layer (WP1–WP4)\nPrincipal Investigator: Prof. Kuan-Ting Lai", {
      x: 0.55, y: 3.85, w: 8.9, h: 0.7,
      fontSize: 12, color: TEAL_TINT, fontFace: FF, lineSpacingMultiple: 1.3,
    });
  }

  /* ── 02 · THE HEADLINE ──────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "This period", "The hard KPI is now measured, not inferred");
    const on = kpi("ros2_shield_on"), off = kpi("ros2_shield_off");
    const dyn = has("ros2_shield_on_dynamic") ? kpi("ros2_shield_on_dynamic") : null;
    const rows = [["Configuration", "P0 escape rate", "P0 ticks", "Unmeas.", "KPI-grade"]];
    rows.push(["Guardrail OFF (control)", n(off.p0_violation_escape_rate, 6),
      off.p0_violation_ticks, off.p0_ticks_not_measurable, off.kpi_grade ? "yes" : "no"]);
    rows.push(["Guardrail ON", n(on.p0_violation_escape_rate, 1),
      on.p0_violation_ticks, on.p0_ticks_not_measurable, on.kpi_grade ? "yes" : "no"]);
    if (dyn) {
      rows.push(["Guardrail ON + dynamic NFZ", n(dyn.p0_violation_escape_rate, 1),
        dyn.p0_violation_ticks, dyn.p0_ticks_not_measurable, dyn.kpi_grade ? "yes" : "no"]);
    }
    table(s, rows, [0.34, 0.18, 0.14, 0.18, 0.16], 0.55, 1.72, 0.44,
      [[2, 1], [3, 1]]);
    card(s, 0.55, 3.7, 8.9, 1.25, ic.check, "What changed",
      "The escape rate used to be INFERRED from whether the Shield had acted — and every branch that raises a violation also appends a repair, so that test could never return non-zero. The Shield now records a re-check of the action it flew.");
    badge(s, next() + 1);
  }

  /* ── 03 · THE MEETING REQUEST, ANSWERED ─────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "19 August review", "“Hold 10 m from a person”, flown");
    const off = metrics("ros2_ped_off"), on = metrics("ros2_ped_on");
    const koff = kpi("ros2_ped_off"), kon = kpi("ros2_ped_on");
    const rows = [["", "Guardrail OFF", "Guardrail ON"]];
    rows.push(["Time inside the 10 m ring", n(off.standoff_s, 1) + " s", n(on.standoff_s, 1) + " s"]);
    rows.push(["Closest approach", n(off.standoff_min_range_m, 2) + " m", n(on.standoff_min_range_m, 2) + " m"]);
    rows.push(["P0 escape rate", n(koff.p0_violation_escape_rate, 6), n(kon.p0_violation_escape_rate, 1)]);
    rows.push(["Mission target reached", off.frac_within_30m ? "yes" : "no", on.frac_within_30m ? "yes" : "no"]);
    rows.push(["KPI-grade", koff.kpi_grade ? "yes" : "no", kon.kpi_grade ? "yes" : "no"]);
    table(s, rows, [0.4, 0.3, 0.3], 0.55, 1.65, 0.36, [[1, 2], [2, 2], [3, 2]]);
    card(s, 0.55, 3.92, 8.9, 1.25, ic.walk, "How to read this",
      "Both runs reach the target. The subject position is DECLARED, not perceived — this rail has no camera, so the measurement is of the Shield, which the review confirmed is the deliverable.");
    badge(s, next() + 1);
  }

  /* ── 04 · THE METRIC THAT WAS WRONG ─────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Correction", "A metric that measured the wrong thing");
    const rows = [["Flight", "det_hit_rate", "frac_on_target", "p95 error", "Target off-frame"]];
    for (const [tag, label] of [["city_full", "Populated city, no lock"],
                                ["city_kpi", "Populated city (b)"],
                                ["demo_traffic", "Distractors"],
                                ["city_demo", "Pedestrians only"]]) {
      if (!has(tag)) continue;
      const a = trackAccuracy(tag);
      if (!a) continue;
      rows.push([label, n(metrics(tag).det_hit_rate, 3), pct(a.onTarget),
        n(a.p95, 1) + " px", String(a.outOfFov)]);
    }
    table(s, rows, [0.32, 0.17, 0.19, 0.16, 0.16], 0.55, 1.72, 0.42, [[1, 2]]);
    card(s, 0.55, 4.0, 8.9, 1.2, ic.warn, "Why it mattered",
      "det_hit_rate counts inferences that produced ANY box — a box on a parked lookalike scores like a box on the target. It is a detector-liveness rate. The flight with the best reported rate was the worst tracker, including frames where the target was outside the camera entirely. frac_on_target scores against the ground truth already present in every flight log.");
    badge(s, next() + 1);
  }

  /* ── 05 · THE FIX ───────────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Instance lock", "Binding the controller to one vehicle");
    const before = trackAccuracy("city_full");
    const after = trackAccuracy("lock_on") || trackAccuracy("city_locked");
    const rows = [["", "Lock off", "Lock on"]];
    if (before && after) {
      rows.push(["Boxes on the correct vehicle", pct(before.onTarget), pct(after.onTarget)]);
      rows.push(["Median error", n(before.median, 1) + " px", n(after.median, 1) + " px"]);
      rows.push(["p95 error", n(before.p95, 1) + " px", n(after.p95, 1) + " px"]);
      rows.push(["Detections with target off-frame", String(before.outOfFov), String(after.outOfFov)]);
    }
    table(s, rows, [0.44, 0.28, 0.28], 0.55, 1.62, 0.36, [[1, 2], [4, 2]]);
    card(s, 0.55, 3.52, 4.3, 1.6, ic.eye, "Gate, tightened",
      "0.28 → 0.12 of image width. Real tracking moves the box a median of 0.0 px per tick, so the old gate admitted thirteen times that — and passed the two jumps onto the wrong vehicle.");
    card(s, 5.15, 3.52, 4.3, 1.6, ic.chip, "Size consistency",
      "The target measured 20–24 px wide, every wrong box 47–84 px. More than 1.8× different in width is a different object — 59 candidates rejected on the recorded run.");
    badge(s, next() + 1);
  }

  /* ── 06 · THE SCENE ─────────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Scene enrichment", "A street with people and vehicles on it");
    card(s, 0.55, 1.72, 2.85, 1.5, ic.city, "Parked vehicles",
      "12 at the kerb, chosen from 12 models. Spawned once and never touched, so they cost no per-tick RPC at all.");
    card(s, 3.58, 1.72, 2.85, 1.5, ic.road, "Moving traffic",
      "Background vehicles on a shared circuit. These are the expensive ones: about 9 RPC/s each.");
    card(s, 6.60, 1.72, 2.85, 1.5, ic.walk, "Pedestrians",
      "12 on pavements, baked to static meshes; a few pace a verified stretch. The standing majority is free.");
    card(s, 0.55, 3.42, 8.9, 1.5, ic.chart, "Why most of it is static",
      "A moving object costs one pose update per control tick, inside the same loop that runs the detector, whose rate only just clears its 4.0 Hz gate. A real street carries far more parked vehicles than moving ones — so the realistic choice and the affordable one are the same choice. Measured with 29 objects on the street: detector 5.15 Hz, all boxes on the correct vehicle, P0 escape rate 0.0.");
    badge(s, next() + 1);
  }

  /* ── 07 · THE FULL KPI SET ──────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Acceptance", "Five of five KPIs now measured");
    const on = kpi("ros2_shield_on"), off = kpi("ros2_shield_off");
    const eps = (k) => (k.time_to_safe_not_measurable ? "not measurable"
      : k.time_to_safe_episodes === 0 ? "0 — never unsafe"
        : n(k.mean_time_to_safe_s, 1) + " s");
    const mag = (k) => (k.mean_repair_magnitude_mps === null
      ? "— (no repairs)" : n(k.mean_repair_magnitude_mps, 2) + " m/s");
    const rows = [["Grant KPI", "Guardrail OFF", "Guardrail ON"]];
    rows.push(["P0 violation escape rate  (target 0)",
      n(off.p0_violation_escape_rate, 6), n(on.p0_violation_escape_rate, 1)]);
    rows.push(["Fail-safe trigger correctness",
      n(off.failsafe_trigger_correctness, 1), n(on.failsafe_trigger_correctness, 1)]);
    rows.push(["Mean repair magnitude", mag(off), mag(on)]);
    rows.push(["Max repair magnitude", off.max_repair_magnitude_mps === null
      ? "—" : n(off.max_repair_magnitude_mps, 2) + " m/s",
      n(on.max_repair_magnitude_mps, 2) + " m/s"]);
    rows.push(["Mean time to safe", eps(off), eps(on)]);
    table(s, rows, [0.42, 0.29, 0.29], 0.55, 1.62, 0.36, [[1, 2], [5, 2]]);
    card(s, 0.55, 3.85, 8.9, 1.22, ic.chart, "The two that had never been computed",
      "Mean repair magnitude and mean time to safe are named in the grant and had no number anywhere — not in a report, not in a deck — although every field they need has been in the flight logs since the first flight. All 42 delivered runs were rescored without re-flying; every previously published P0 figure reproduced exactly.");
    badge(s, next() + 1);
  }

  /* ── 08 · WHAT THE NEW METRIC FOUND ─────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Why it mattered", "A recovery that never arrived");
    const a = EXTRA.altitude_recovery;
    const rows = [["Climbing back to a " + n(a.floor_m, 0) + " m floor from " +
      n(a.start_m, 0) + " m", "Aiming at the floor", "Aiming inside it"]];
    for (const t of a.samples_s) {
      rows.push(["altitude after " + t + " s",
        n(a.before.at_s[String(t)], 5) + " m", n(a.after.at_s[String(t)], 3) + " m"]);
    }
    rows.push(["enters the band", a.before.enters_band_s === null ? "never"
      : n(a.before.enters_band_s, 1) + " s", n(a.after.enters_band_s, 1) + " s"]);
    table(s, rows, [0.44, 0.28, 0.28], 0.55, 1.62, 0.36, [[4, 1], [4, 2]]);
    card(s, 0.55, 3.68, 8.9, 1.4, ic.warn, "Every existing KPI called this healthy — and each was right to",
      "The emitted action climbs, so it is legal on every tick; the P0 escape rate stayed 0 the whole way down, and the repair count read as a Shield working hard. The action was always fine. The state never became safe. The three KPIs measured until now are all properties of ACTIONS; mean time to safe is the first that is a property of the TRAJECTORY, and it found this within an hour of existing.");
    badge(s, next() + 1);
  }

  /* ── 09 · POLICY DSL ────────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "WP1", "Two rule classes the DSL could not express");
    const c = EXTRA.constraints;
    card(s, 0.55, 1.68, 4.3, 1.62, ic.road, "corridor — the first keep-IN rule",
      "A fence says where you may NOT go; a corridor says the route is the only place you MAY. Centerline, width, altitude band. Distance is measured to the segments, never the vertices.");
    card(s, 5.15, 1.68, 4.3, 1.62, ic.rules, "valid_time — a schedule on any rule",
      "Weekday 07:30–17:30 school curfew, expressed on the fence itself. It is a FIELD, not a rule type — and it is inside policy_hash, so a schedule is part of the audit trail.");
    card(s, 0.55, 3.52, 8.9, 1.55, ic.check, "Where this leaves the schema",
      `${c.n_implemented} constraint classes implemented, against ${c.reference_impl_n_types} in the reference implementation's own policy-dsl package. Both classes are named in the grant's DSL specification and were absent from BOTH codebases, so there was no prior art to copy — and one detail would have been got wrong without reading the spec: a time window is a field any rule may carry, not a constraint class of its own.`);
    badge(s, next() + 1);
  }

  /* ── 10 · SCENARIO SWEEP ────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "WP4", "The sweep harness the report said was not built");
    const k = EXTRA.sweep.counts;
    const stat = (x, label, value, tint) => {
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x, y: 1.68, w: 2.03, h: 1.1, fill: { color: tint ? TEAL : WHITE },
        line: { color: tint ? TEAL : LINE, width: 1 }, rectRadius: 0.08,
      });
      s.addText(String(value), {
        x, y: 1.78, w: 2.03, h: 0.55, fontSize: 30,
        color: tint ? WHITE : BLACK, fontFace: FF, bold: true, align: "center",
      });
      s.addText(label, {
        x, y: 2.32, w: 2.03, h: 0.34, fontSize: 10,
        color: tint ? TEAL_TINT : GREY, fontFace: FF, align: "center",
      });
    };
    stat(0.55, "scenarios", EXTRA.sweep.n_scenarios, true);
    stat(2.84, "passing", k.pass, false);
    stat(5.13, "failing", k.fail, false);
    stat(7.42, "known failures", k.known_failure, false);
    card(s, 0.55, 3.0, 4.3, 2.05, ic.vials, "Runs anywhere, in about a second",
      "Shield plus a kinematic integrator: no simulator, no GPU, no autopilot. That is the difference between a harness that runs on every change and one that runs when somebody remembers. One scenario flies UNSHIELDED and is gated to FAIL on safety — if an unguarded run into a no-fly zone ever scores clean, every other pass here is worthless.");
    card(s, 5.15, 3.0, 4.3, 2.05, ic.warn, "An open defect, kept visible",
      `${EXTRA.sweep.known_failures.join(", ")}: a subject standing exactly on the route. Every heading that makes progress also closes the range, so the Shield holds — no illegal action, the ring never broken — and the mission never arrives. Reported every sweep as a known failure, never as a pass. If it starts passing, that is reported too.`);
    badge(s, next() + 1);
  }

  /* ── 11 · WP1/WP2 ARTEFACTS ─────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "WP1 · WP2", "Three named deliverables, now produced");
    const b = EXTRA.bundles["wgs84_taipei"] || Object.values(EXTRA.bundles)[0];
    card(s, 0.55, 1.68, 2.85, 1.72, ic.lock, "Signed policy bundle",
      `tar.gz of canonical IR + manifest + signature, ${b.bytes} bytes. Reloading REFUSES a tampered IR, a foreign manifest, or a truncated archive.`);
    card(s, 3.58, 1.68, 2.85, 1.72, ic.globe, "WGS84 authoring",
      "The frame the DSL spec calls canonical. Additive: metre policies still load unchanged. A geographic policy with no origin is refused, not defaulted.");
    card(s, 6.60, 1.68, 2.85, 1.72, ic.rules, "Constraint Summary Pack",
      "Every rule in force, with the hash. The prompt renders FROM the pack, so the two cannot disagree.");
    card(s, 0.55, 3.62, 8.9, 1.45, ic.check, "A gap the pack exposed on the way",
      "The prompt handed to the pilot listed fences, the altitude band and the speed cap — and nothing else. On the pedestrian policy, whose headline rule is a 10 m stand-off, it described none of it. The planner could only discover that rule by being repaired against it, which is the opposite of what a prefix compiler is for.");
    badge(s, next() + 1);
  }

  /* ── 12 · THE RETARGET, FLOWN ───────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "The review's question, flown",
      "One flight, one policy, one word changed");
    const R = retargetSplit("retarget_demo2");
    // pre/post can each come back all-unscorable, which is a REPORTABLE state
    // and not an error: it is exactly what a correct scorer says about the
    // pedestrian half of a flight whose truth was never logged. Read both
    // counts and let the card say which it is, rather than dereferencing a
    // number that is not there and killing the whole deck build.
    const preN = R ? R.pre.n : 0;
    const postAll = R ? R.post.n + R.post.unscorable : 0;
    if (R && preN > 0) {
      card(s, 0.55, 1.68, 4.35, 1.62, ic.walk, "What changed, and what did not",
        `At t+${R.ev.t.toFixed(1)} s the operator changed a PHRASE: ${R.ev.from.object} -> ${R.ev.to.object}. The class became ${R.ev.to.class}, so a different rule bound and the enforced ring moved 5 m -> 10 m. Same aircraft, same policy, same hash. A tracker returns an ID, never a class, so it cannot be asked this question at all.`);
      card(s, 5.10, 1.68, 4.35, 1.62, ic.warn, "A rule that was hashed and inert",
        `Building it found the 10 m rule binding "pedestrian" while the phrase produced "person". Exact-string compare, so across a whole flight with a human subject it fired 0 times and the 5 m catch-all applied. No violation is indistinguishable from no rule. Synonyms are now canonicalised, and an unreachable rule is a start-up refusal.`);
      card(s, 0.55, 3.44, 4.35, 1.62, ic.check, "Tracking, scored honestly",
        `Before the retarget: ${pct(R.pre.onTarget)} on target, ${n(R.pre.median, 1)} px median over ${preN} detections. After it: UNMEASURED. The log carried one ground truth — the car — so the ${postAll} later detections were being compared to an object behind the aircraft. Truth now follows the subject.`);
      card(s, 5.10, 3.44, 4.35, 1.62, ic.aim, "What the flight does not show yet",
        "The ring did not fire: the position the Shield was SERVED never came inside 14.7 m, and a 10 m ring cannot fire at 14.7 m. The capability is proven in the sweep; the video shows the retarget but not its consequence. Stated as the open item it is.");
    }
    badge(s, next() + 1);
  }

  /* ── 13 · WHAT IS OPEN ──────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Remaining work", "Ordered by contribution to acceptance");
    const rg = EXTRA.rate_gate;
    const items = [
      ["1", "Perception on the KPI-grade rail",
       "ArduPilot SITL has no renderer, so all tracking evidence sits outside the contractual gate. The largest remaining item"],
      ["2", "The camera rail still misses its own rate gate",
       `Pre-registered at loop ≥ ${rg.gate.loop_hz_min} Hz and detector ≥ ${rg.gate.det_hz_min} Hz; ${rg.n_meeting_gate} of ${rg.n_runs} recorded runs meet it`],
      ["3", "Low-altitude policies select the cruise-band map",
       "follow_pedestrian.yaml permits descent to 4 m and loads the 6-14 m map; ground_2to4 ends at exactly 4 m so it never applies, and NOTHING maps 4-6 m"],
      ["4", "The retarget flight does not yet show the ring change",
       "The aircraft never closed to 10 m of the position the Shield was served, so the rule had nothing to act on; needs stronger pedestrian acquisition"],
      ["5", "The wedge: a repaired action can still be a stuck mission",
       "A subject on the route makes every progressing heading also a closing one. The Shield holds and the mission never arrives; it needs a planner, not a filter"],
    ];
    let y = 1.82;
    items.forEach(([nn, t, b]) => {
      s.addShape(pres.shapes.ROUNDED_RECTANGLE, {
        x: 0.55, y, w: 0.38, h: 0.38,
        fill: { color: TEAL }, line: { color: TEAL }, rectRadius: 0.05,
      });
      s.addText(nn, {
        x: 0.55, y, w: 0.38, h: 0.38, fontSize: 11, color: WHITE, fontFace: FF,
        bold: true, align: "center", valign: "middle",
      });
      s.addText(t, {
        x: 1.05, y: y - 0.02, w: 8.4, h: 0.26, fontSize: 12, color: INK, fontFace: FF, bold: true,
      });
      s.addText(b, {
        x: 1.05, y: y + 0.22, w: 8.4, h: 0.26, fontSize: 10, color: GREY, fontFace: FF,
      });
      y += 0.62;
    });
    badge(s, next() + 1);
  }

  /* ── 08 · DELIVERABLES ──────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    heading(s, "Deliverables", "Accompanying this deck");
    const rows = [["Artefact", "File", "Size"]];
    rows.push(["This deck", "docs/VLA-Guardrail-Sept2026.pptx / .pdf", "-"]);
    rows.push(["Populated city, lock on", "docs/video/city_locked.mp4",
      videoMb("demo/out/city_locked/city_locked_final.mp4")]);
    rows.push(["Meeting pack (EN + ID script, Q&A)", "docs/MEETING-PACK-Sept2026.md", "-"]);
    rows.push(["Scenario sweep results", "docs/data/scenario_sweep.json", "-"]);
    rows.push(["Remaining-work checklist", "docs/CHECKLIST-remaining-work.md", "-"]);
    rows.push(["Replay bundles (WP4)", "bundles/*.replay.tar.gz", "-"]);
    rows.push(["Findings this period",
      `docs/FINDING-*.md (${findingsSince("2026-09")} documents)`, "-"]);
    table(s, rows, [0.34, 0.48, 0.18], 0.55, 1.72, 0.42);
    s.addText("Every figure in this deck is read from demo/out/<tag>/metrics.json and kpi.json at build time; tracking accuracy is recomputed from the flight logs. Videos ship as separate files and are not embedded.", {
      x: 0.55, y: 3.72, w: 8.9, h: 0.6,
      fontSize: 10, color: GREY, fontFace: FF, italic: true, lineSpacingMultiple: 1.3,
    });
    badge(s, next() + 1);
  }

  /* ── 09 · CLOSING ───────────────────────────────────────────────────── */
  {
    const s = pres.addSlide();
    darkBase(s, "Summary");
    const on = kpi("ros2_shield_on");
    s.addText("P0 violation escape rate", {
      x: 0.55, y: 1.6, w: 8.9, h: 0.4,
      fontSize: 14, color: TEAL_TINT, fontFace: FF,
    });
    s.addText(n(on.p0_violation_escape_rate, 1), {
      x: 0.55, y: 2.0, w: 8.9, h: 1.1,
      fontSize: 68, color: WHITE, fontFace: FF, bold: true,
    });
    s.addText("measured — not inferred — on the grant's canonical ArduPilot topology,\nwith zero unmeasurable ticks, across three configurations.", {
      x: 0.55, y: 3.2, w: 8.9, h: 0.8,
      fontSize: 13, color: TEAL_TINT, fontFace: FF, lineSpacingMultiple: 1.3,
    });
  }

  const out = path.join(REPO, "docs/VLA-Guardrail-Sept2026.pptx");
  await pres.writeFile({ fileName: out });
  console.log("wrote " + out);
}

main().catch((e) => { console.error(e); process.exit(1); });
