(fn UpdateEffSpeed ()
  (Variables|Default|SetTicks (+ {Ticks} 1))
  (if (== (Math|Integer|%(Integer) {Ticks} 2) 0)
    (Variables|Default|SetDbgMe (Transformation|GetActorLocation))
    (Variables|Default|SetDbgFwd (Transformation|GetActorForwardVector))
    (Variables|Default|SetRgt (Transformation|GetActorRightVector))
    (Variables|Default|SetNowT (Utilities|Time|GetGameTimeInSeconds))
    (Variables|Default|SetInBox false)
    (Variables|Default|SetHasJ false)
    (Variables|Default|SetConflict false)
    (Variables|Default|SetGive false)
    (Variables|Default|SetOncGo false)
    (Variables|Default|SetExitBlk false)
    (Variables|Default|SetExitPed false)
    (Variables|Default|SetJEdge 99999.0)
    (Variables|Default|SetNJi -1)
    (for _k (range (Utilities|Array|Length {Junctions}))
      (Variables|Default|SetTmpD (- (Utilities|Array|Get(acopy) {Junctions} _k) {DbgMe}))
      (if (and (< (Math|Float|Absolute(Float) (.x {TmpD})) @BOX@)
               (< (Math|Float|Absolute(Float) (.y {TmpD})) @BOX@))
        (Variables|Default|SetInBox true))
      (Variables|Default|SetTmpA (Math|Vector|DotProduct {TmpD} {DbgFwd}))
      (if (and (and (> {TmpA} @JNEAR@) (< (- {TmpA} @JNEAR@) {JEdge}))
               (and (< {TmpA} @JFAR@)
                    (< (Math|Float|Absolute(Float) (Math|Vector|DotProduct {TmpD} {Rgt})) @BOX@)))
        (Variables|Default|SetJEdge (- {TmpA} @JNEAR@))
        (Variables|Default|SetNextJ (Utilities|Array|Get(acopy) {Junctions} _k))
        (Variables|Default|SetNJi _k)
        (Variables|Default|SetHasJ true)))
    (Variables|Default|SetCheckJ (and {HasJ} (not {InBox})))
    (if {CheckJ}
      (Variables|Default|SetJOut (Utilities|Array|Get(acopy) {JExit} {NJi}))
      (Variables|Default|SetUOut (Math|Vector|MakeVector (Math|Trig|Cos(Degrees) (.z {JOut}))
                                                         (Math|Trig|Sin(Degrees) (.z {JOut})) 0.0))
      (Variables|Default|SetPh (Math|Float|%(Float)
        (+ (- {NowT} (+ (Utilities|Array|Get(acopy) {JOff} {NJi})
                        (select (< (Math|Float|Absolute(Float) (.x {DbgFwd})) (Math|Float|Absolute(Float) (.y {DbgFwd}))) @HALF@ 0.0)))
           @PHASE_PAD@)
        @CYCLE@))
      (Variables|Default|SetSig (select (< {Ph} @GREEN@) 0 (select (< {Ph} @AMBER_END@) 1 2))))
    (Variables|Default|SetGapCm 99999.0)
    (Variables|Default|SetTmpB 99999.0)
    (Variables|Default|SetMinNow 99999.0)
    (bind _cars (Actor|GetAllActorsOfClass "__CAR__"))
    (for _car _cars
      (Variables|Default|SetTmpE (Transformation|GetActorLocation :self _car))
      (Variables|Default|SetTmpD (- {TmpE} {DbgMe}))
      (if (> (Math|Vector|VectorLengthXY {TmpD}) 1.0)
        (Variables|Default|SetMinNow (Math|Float|Min(Float) {MinNow} (Math|Vector|VectorLengthXY {TmpD})))
        (Variables|Default|SetOFwd (Transformation|GetActorForwardVector :self _car))
        (Variables|Default|SetTmpA (Math|Vector|DotProduct {TmpD} {DbgFwd}))
        (Variables|Default|SetPar (Math|Vector|DotProduct {OFwd} {DbgFwd}))
        (if (> {TmpA} 0.0)
          (if (> {Par} 0.5)
            (if (or (< (Math|Float|Absolute(Float) (Math|Vector|DotProduct {TmpD} {Rgt})) @LANE@)
                    (< (Math|Vector|VectorLengthXY {TmpD}) @ARC_LEADER@))
              (Variables|Default|SetGapCm (Math|Float|Min(Float) {GapCm} {TmpA})))
            (else
              (if (and (< {TmpA} 900.0)
                       (< (Math|Float|Absolute(Float) (Math|Vector|DotProduct {TmpD} {Rgt})) @LANE@))
                (if (> {Par} 0.0)
                  (Variables|Default|SetGapCm (Math|Float|Min(Float) {GapCm} {TmpA}))
                  (else
                    (Variables|Default|SetTmpB (Math|Float|Min(Float) {TmpB} {TmpA}))))))))
        (if {CheckJ}
          (bind _ov (CallFunction|SpeedOf :self _car))
          (Variables|Default|SetOV _ov)
          (Variables|Default|SetTmpD (- {TmpE} {NextJ}))
          (Variables|Default|SetInside (and (< (Math|Float|Absolute(Float) (.x {TmpD})) @BOX@)
                                            (< (Math|Float|Absolute(Float) (.y {TmpD})) @BOX@)))
          (Variables|Default|SetTA2 (* -1.0 (+ (* (.x {TmpD}) (.x {OFwd})) (* (.y {TmpD}) (.y {OFwd})))))
          (Variables|Default|SetOLat (Math|Float|Absolute(Float) (- (* (.y {TmpD}) (.x {OFwd})) (* (.x {TmpD}) (.y {OFwd})))))
          (if (and (< {Par} 0.7) {Inside})
            (if (not (or (and (> (+ (* (.x {OFwd}) (.x {UOut})) (* (.y {OFwd}) (.y {UOut}))) @EXIT_QUARTER@)
                              (> {Par} @NEG_EXIT_QUARTER@))
                         (and (< {Par} -0.7) (< {TA2} @NEG_ONCOMING_PASSED@))))
              (Variables|Default|SetConflict true))
            (else
              (if (and (> (.z {NextJ}) 0.5) (< {OLat} @BOX@))
                (if (and (< {Par} -0.7) (and (> {TA2} @BOX@) (< {TA2} @GIVEWAY_FAR@)))
                  (Variables|Default|SetGive true)
                  (if (and (> {OV} @V_STOPPED@)
                           (< (- {TA2} @STOP@) (+ (/ (* {OV} {OV}) @TWO_STOP_DECEL@) @SNEAK_SLACK@)))
                    (Variables|Default|SetOncGo true))))))
          (Variables|Default|SetTmpC (+ (* (- (.x {TmpE}) (.x {JOut})) (.x {UOut}))
                                        (* (- (.y {TmpE}) (.y {JOut})) (.y {UOut}))))
          (if (and (and (> {TmpC} @NEG_BOX@) (< {TmpC} @EXIT_CLEAR@))
                   (and (< (Math|Float|Absolute(Float) (- (* (- (.y {TmpE}) (.y {JOut})) (.x {UOut}))
                                                          (* (- (.x {TmpE}) (.x {JOut})) (.y {UOut}))))
                           @LANE@)
                        (and (> (+ (* (.x {OFwd}) (.x {UOut})) (* (.y {OFwd}) (.y {UOut}))) 0.5)
                             (< {OV} @V_SLOW@))))
            (Variables|Default|SetExitBlk true)))))
    (Variables|Default|SetStopCm 99999.0)
    (if (< {Ticks} 3)
      (Variables|Default|SetStillDone -1)
      (Variables|Default|SetStillCPrev -1)
      (Variables|Default|SetSneakJ -1)
      (Variables|Default|SetPrevNJ -1))
    (Variables|Default|SetStillSeen false)
    (Variables|Default|SetStillBest 99999)
    (Variables|Default|SetEHit false)
    (Variables|Default|SetCloseHit false)
    (for _c {Crossings}
      (Variables|Default|SetCIdx (Math|Float|Truncate (.z _c)))
      (Variables|Default|SetCAhead (Math|Integer|%(Integer) (+ (- {CIdx} {Idx}) {NPts}) {NPts}))
      (Variables|Default|SetCA2 {CAhead})
      (if (> {CAhead} 17)
        (Variables|Default|SetCA2 (+ 1000 (- {NPts} {CAhead}))))
      (if (and (== {CIdx} {StillDone})
               (and (> {CAhead} 17) (< {CAhead} (- {NPts} 4))))
        (Variables|Default|SetStillDone -1))
      (Variables|Default|SetExempt (or (== {CIdx} {StillDone})
                                       (and (== {CIdx} {StillCPrev}) (>= {StillRun} 6.0))))
      (Variables|Default|SetIsExit false)
      (if (and {CheckJ} (and (>= {CAhead} 3) (<= {CAhead} @EXIT_AHEAD@)))
        (Variables|Default|SetIsExit
          (and (> (+ (* (- (.x _c) (.x {NextJ})) (.x {DbgFwd})) (* (- (.y _c) (.y {NextJ})) (.y {DbgFwd}))) @NEG_EXIT_BACK@)
               (< (Math|Vector|VectorLengthXY (Math|Vector|MakeVector (- (.x _c) (.x {NextJ})) (- (.y _c) (.y {NextJ})) 0.0)) @EXIT_NEAR@))))
      (Variables|Default|SetInWin (or (<= {CAhead} 17) (>= {CAhead} (- {NPts} 4))))
      (if (or {InWin} {IsExit})
        (Variables|Default|SetTmpE (- (Utilities|Array|Get(acopy) {Route} (Math|Integer|%(Integer) (+ {CIdx} 1) {NPts}))
                                      (Utilities|Array|Get(acopy) {Route} {CIdx})))
        (Variables|Default|SetOFwd (Math|Vector|Normalize (Math|Vector|MakeVector (.x {TmpE}) (.y {TmpE}) 0.0)))
        (bind _peds (Actor|GetAllActorsOfClass "__PED__"))
        (for _p _peds
          (Variables|Default|SetTmpE (- (Transformation|GetActorLocation :self _p) _c))
          (Variables|Default|SetPedSpd (Math|Vector|VectorLengthXY (Transformation|GetVelocity :self _p)))
          (if (and {IsExit}
                   (and (> {PedSpd} 20.0)
                        (and (< (Math|Float|Absolute(Float)
                                  (+ (* (.x {TmpE}) (.x {OFwd})) (* (.y {TmpE}) (.y {OFwd})))) 300.0)
                             (< (Math|Float|Absolute(Float)
                                  (- (* (.y {TmpE}) (.x {OFwd})) (* (.x {TmpE}) (.y {OFwd})))) @EXIT_PED_SPAN@))))
            (Variables|Default|SetExitPed true))
          (if {InWin}
            (if (and (< (Math|Float|Absolute(Float)
                          (+ (* (.x {TmpE}) (.x {OFwd})) (* (.y {TmpE}) (.y {OFwd})))) 300.0)
                     (< (Math|Float|Absolute(Float)
                          (- (* (.y {TmpE}) (.x {OFwd})) (* (.x {TmpE}) (.y {OFwd})))) 800.0))
              (if (< {PedSpd} 20.0)
                (Variables|Default|SetStillSeen true)
                (if (< {CA2} {StillBest})
                  (Variables|Default|SetStillBest {CA2})
                  (Variables|Default|SetStillC {CIdx})))
              (if (and (>= {CAhead} 3) (<= {CAhead} 17))
                (if (or (> {PedSpd} 20.0) (not {Exempt}))
                  (Variables|Default|SetStopCm (Math|Float|Min(Float) {StopCm} (- (* 150.0 {CAhead}) 650.0)))
                  (Variables|Default|SetPedTicks (+ {PedTicks} 1)))
                (else
                  (Variables|Default|SetTmpD (- (Transformation|GetActorLocation :self _p) {DbgMe}))
                  (Variables|Default|SetTmpA (Math|Vector|DotProduct {TmpD} {DbgFwd}))
                  (if (and (> {TmpA} -100.0)
                           (and (< {TmpA} 900.0)
                                (< (Math|Float|Absolute(Float) (Math|Vector|DotProduct {TmpD} {Rgt})) 300.0)))
                    (if (or (> {PedSpd} 20.0) (not {Exempt}))
                      (Variables|Default|SetStopCm 0.0)
                      (Variables|Default|SetEHit true)
                      (if (and (> {PedSpd} 20.0) (< {TmpA} 400.0))
                        (Variables|Default|SetCloseHit true))))
                  (if (and (<= {CAhead} 2) (> {CurSpeed} 50.0))
                    (if (> {PedSpd} 20.0)
                      (Variables|Default|SetPedViol (+ {PedViol} 1))
                      (else
                        (Variables|Default|SetPedPassStill (+ {PedPassStill} 1))))))))))))
    (if {StillSeen}
      (if (not (== {StillC} {StillCPrev}))
        (Variables|Default|SetStillRun 0.0)
        (Variables|Default|SetStillCPrev {StillC}))
      (if (< {CurSpeed} 10.0)
        (Variables|Default|SetStillRun (+ {StillRun} (* 2.0 {Dt}))))
      (if (>= {StillRun} 6.0)
        (Variables|Default|SetStillDone {StillCPrev}))
      (else
        (Variables|Default|SetStillRun 0.0)
        (Variables|Default|SetStillCPrev -1)))
    (if {EHit}
      (Variables|Default|SetEStops (+ {EStops} 1))
      (if (> {CurSpeed} 50.0)
        (Variables|Default|SetPedCorr (+ {PedCorr} 1))))
    (if (and {CloseHit} (> {CurSpeed} 50.0))
      (Variables|Default|SetPedClose (+ {PedClose} 1)))
    (if (or (not {CheckJ}) (!= {NJi} {SneakJ}))
      (Variables|Default|SetSneakJ -1))
    (if (not {CheckJ})
      (Variables|Default|SetHeldTurn 0.0))
    (Variables|Default|SetHold 0)
    (if {CheckJ}
      (Variables|Default|SetDLine (- (+ {JEdge} @JNEAR@) @STOP@))
      (if (> {DLine} @NEG_COMMIT@)
        (Variables|Default|SetSneaking (== {SneakJ} {NJi}))
        (if (and (not {Sneaking})
                 (and (== {Sig} 1)
                      (and (> (.z {NextJ}) 0.5)
                           (and (>= {HeldTurn} @SNEAK_HELD@)
                                (and (< {CurSpeed} @V_STOPPED@)
                                     (and (< {DLine} @COMMIT@)
                                          (and (< (- {Ph} @GREEN@) @SNEAK_LATEST@)
                                               (not (or (or {Conflict} {OncGo}) (or {ExitBlk} {ExitPed}))))))))))
          (Variables|Default|SetSneaking true)
          (Variables|Default|SetSneakJ {NJi})
          (Variables|Default|SetSneaks (+ {Sneaks} 1)))
        (Variables|Default|SetTarget {DLine})
        (if (and (== {Sig} 2) (not {Sneaking}))
          (Variables|Default|SetHold 1)
          (else
            (if (and (== {Sig} 1)
                     (and (not {Sneaking})
                          (>= {DLine} (- (/ (* {CurSpeed} {CurSpeed}) @TWO_STOP_DECEL@) @COMMIT@))))
              (Variables|Default|SetHold 2))))
        (if (== {Hold} 0)
          (Variables|Default|SetHold
            (select {Conflict} 3
              (select (select {Sneaking} {OncGo} {Give}) 4
                (select {ExitBlk} 5
                  (select (and {ExitPed} (and (== {Sig} 0) (< {Ph} @WALK@))) 6 0)))))
          (if (and (or (== {Hold} 3) (== {Hold} 4)) (and (> (.z {NextJ}) 0.5) (== {Sig} 0)))
            (Variables|Default|SetHeldTurn (+ {HeldTurn} (* 2.0 {Dt})))
            (else
              (if (> {CurSpeed} @V_STOPPED@)
                (Variables|Default|SetHeldTurn 0.0))))
          (if (and (> {Hold} 0) (< {DLine} (- (/ (* {CurSpeed} {CurSpeed}) @TWO_MAX_DECEL@) @COMMIT@)))
            (if (== {Hold} 3)
              (Variables|Default|SetTarget (- {JEdge} 300.0))
              (Variables|Default|SetHold 7)
              (Variables|Default|SetLateHold (+ {LateHold} 1))
              (else
                (Variables|Default|SetHold 0))))
          (if (and {Sneaking} (and (> {Hold} 0) (!= {Hold} 7)))
            (Variables|Default|SetSneakJ -1)))
        (if (> {Hold} 0)
          (if (or (== {Hold} 1) (== {Hold} 2))
            (Variables|Default|SetSigHolds (+ {SigHolds} 1)))
          (if (or (== {Hold} 3) (or (== {Hold} 4) (== {Hold} 7)))
            (Variables|Default|SetYieldTicks (+ {YieldTicks} 1)))
          (Variables|Default|SetStopCm (Math|Float|Min(Float) {StopCm} {Target})))
        (else
          (if {Conflict}
            (Variables|Default|SetLateHold (+ {LateHold} 1))
            (Variables|Default|SetHold 7)
            (Variables|Default|SetTarget (- {JEdge} 300.0))
            (Variables|Default|SetStopCm (Math|Float|Min(Float) {StopCm} {Target})))))
      (if (and (> {Hold} 0)
               (and (< {CurSpeed} @V_STOPPED@)
                    (and (and (<= {Target} {StopCm}) (<= {StopCm} (- {GapCm} @QUEUE@)))
                         (and (< (- (+ {JEdge} @JNEAR@) @CAR_HALF_LEN@) @ZEBRA_OUTER@)
                              (> (+ (+ {JEdge} @JNEAR@) @CAR_HALF_LEN@) @ZEBRA_INNER@)))))
        (Variables|Default|SetZebraWait (+ {ZebraWait} 1)))
      (if (and (== {NJi} {PrevNJ}) (and (> {PrevDL} @NEG_RED_TOL@) (and (<= {DLine} @NEG_RED_TOL@) (and (== {Sig} 2) (and (not {Sneaking}) (> {CurSpeed} @V_STOPPED@))))))
        (Variables|Default|SetRedViol (+ {RedViol} 1)))
      (Variables|Default|SetPrevDL {DLine})
      (Variables|Default|SetPrevNJ {NJi})
      (else
        (Variables|Default|SetPrevNJ -1)))
    (if (and {InBox} (< {CurSpeed} @V_STOPPED@))
      (Variables|Default|SetBoxStill (+ {BoxStill} (* 2.0 {Dt}))))
    (if (< {Ticks} 3)
      (Variables|Default|SetMinEver 99999.0))
    (Variables|Default|SetMinEver (Math|Float|Min(Float) {MinEver} {MinNow}))
    (if (< {MinNow} 400.0)
      (Variables|Default|SetCloseTicks (+ {CloseTicks} 1)))
    (Variables|Default|SetTmpA (Math|Float|Clamp(Float) (/ {TmpB} (+ 700.0 (* 1.8 {CurSpeed}))) 0.0 1.0))
    (Variables|Default|SetEffSpeed (Math|Float|Min(Float) {SpeedCmS}
      (Math|Float|Max(Float) 60.0 (* {SpeedCmS} (* {TmpA} {TmpA})))))))
